### ISSUE TITLE
Query about .sb3 file (Nov 2019)

### ISSUE THREAD

**Issue by ninaszymor** [raspberrypilearning/cd-advanced-scratch-sushi#12]
One of the volunteers translating Falling Stars has left this comment: In the .sb3 there are variables named x-speed and x-velocity (and y-*). I think x-speed is actually the velocity, while x-velocity should be start-x . Same for y-*. I don't know the project well so rather than trying to figure it out myself, it might be easier if @PhilipHarney or @daraghbroderick  have a look.

**Comment by PhilipHarney** [comment]
Yeah… I don't actually like how I coded this project looking back on it now. It's needlessly complex to achieve what it does. I'd be inclined to drastically simplify the physics code rather than trying to fix it, if there actually is an issue.

**Comment by pablisch** [comment]
In the short term, I have changed _velocity_ to speed and _speed_ to speed-adjuster to make the relationship more obvious.
